name: Semantic Release

on:
  push:
    branches: [ development ]

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci -f

      - name: Semantic Release
        env:
          GITSECRET_TOKEN: ${{ secrets.GITSECRET_TOKEN }}
        run: npx semantic-release
